VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:feat/faster-rust-tool-install AS rust-ci
# IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.1.24 AS rust-ci
# Use when debugging cat-ci locally.
# IMPORT ../../catalyst-ci/earthly/rust AS rust-ci
IMPORT .. AS rust-local

# Run build using the most efficient host tooling
# CI Automated Entry point.
build:
    FROM rust-local+build

    SAVE ARTIFACT target/release/cbork cbork

# Test which runs check with all supported host tooling.  Needs qemu or rosetta to run.
# Only used to validate tooling is working across host toolsets.
build-all-hosts:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +build-hosted
