VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust::v3.2.11 AS rust-ci

IMPORT .. AS rust-local

# Run build using the most efficient host tooling
# CI Automated Entry point.
build:
    FROM rust-local+build

    SAVE ARTIFACT target/release/cbork cbork
