VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust::rust/bump-compiler-to-1.83 AS rust-ci


IMPORT .. AS rust-local

# Run build using the most efficient host tooling
# CI Automated Entry point.
build-cbork:
    FROM rust-local+build

    SAVE ARTIFACT target/release/cbork cbork
