[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "wasm32-unknown-unknown",
    "wasm32-wasip1",
    "wasm32-wasip2",
]

[advisories]
version = 2
ignore = [
    { id = "RUSTSEC-2020-0168", reason = "`mach` is used by wasmtime and we have no control over that." },
    { id = "RUSTSEC-2021-0145", reason = "we don't target windows, and don;t use a custom global allocator." },
]

[bans]
multiple-versions = "warn"
wildcards = 'deny'
deny = [
    { crate = "openssl", use-instead = "rustls" },
    { crate = "openssl-sys", use-instead = "rustls" },
    "libssh2-sys",
]
skip = []
skip-tree = [
    { crate = "windows-sys@0.48.0", reason = "a foundational crate for many that bumps far too frequently to ever have a shared version" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

# List of URLs for allowed Git repositories
allow-git = [
    "https://github.com/input-output-hk/hermes.git",
    "https://github.com/input-output-hk/catalyst-pallas.git",
    "https://github.com/bytecodealliance/wasmtime",
    "https://github.com/aldanor/hdf5-rust",
]

[licenses]
version = 2
unused-allowed-license = "allow"
confidence-threshold = 0.93
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "BlueOak-1.0.0",
    "Apache-2.0 WITH LLVM-exception",
    "CC0-1.0",
    "ISC",
    "Unicode-3.0",
    "MPL-2.0",
]
exceptions = []

[[licenses.clarify]]
crate = "byte-array-literals"
expression = "Apache-2.0 WITH LLVM-exception"
license-files = [{ path = "../../../LICENSE", hash = 0x001c7e6c }]

[[licenses.clarify]]
crate = "hdf5-src"
expression = "MIT"
license-files = [{ path = "../LICENSE-MIT", hash = 0x001c7e6c }]

[[licenses.clarify]]
crate = "ring"
expression = "MIT"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
