; All encoders/decoders of this specification must follow deterministic cbor encoding rules
; https://datatracker.ietf.org/doc/html/draft-ietf-cbor-cde-06

block = [
    block-header,
    block-data,
    validator-signature,
]

block-header = [
    chain-id: UUID, ; UUID v7
    height: int,
    timestamp: #6.1(uint .ge 1722470400), ; Epoch-based date/time
    prev-block-id: hash-bytes, ; hash of the previous block
    ?ledger-type: UUID, ; UUID v4
    ?purpose-id: UUID, ; UUID v7
    ?validator,
    ~metadata,
]

block-data = encoded-cbor

UUID = #6.37(bytes) ; UUID type

kid = hash-bytes ; hash of the x509/c509 certificate

validator = (kid / [2* kid])
metadata = [ *any ]

validator-signature = (bytes / [2* bytes])

;# include hash
