classDiagram
    direction LR

    class Last {
        type: "=Intermediate.Document Type"
        id: "=Intermediate.Document ID"
        ver: ">Intermediate.Document ID"
        parameters: "=Intermediate.Document Parameters"
        chain.height: -2
        chain.document_ref: "=Intermediate"

        author(Intermediate.Catalyst ID)
    }
    style Last stroke:#f60,stroke-width:4px

    class Intermediate {
        type: "=First.Document Type"
        id: "=First.Document ID"
        ver: ">First.Document ID"
        parameters: "=First.Document Parameters"
        chain.height: 1
        chain.document_ref: "=First"

        author(First.Catalyst ID)
    }
    style Intermediate stroke:#f60,stroke-width:4px

    class First {
        type: "Document Type"
        id: "Document ID"
        ver: "=Document ID"
        parameters: "Document Parameters"
        chain.height: 0
        chain.document_ref: None

        author(Catalyst ID)
    }
    style First stroke:#f60,stroke-width:4px

    Last --|> Intermediate : chains to
    Intermediate --|> First : chains to

    class Invalid_Chain {
        type: "=First.Document Type"
        id: "=First.Document ID"
        ver: ">Intermedisate.Document ID"
        parameters: "=First.Document Parameters"
        chain.height: 1
        chain.document_ref: "=First"

        author(First.Catalyst ID)
    }

    Invalid_Chain --|> First : Invalidly chains to
    style Invalid_Chain fill:#100,stroke:#f00,stroke-width:4px


    class After_Final {
        type: "=Final.Document Type"
        id: "=Final.Document ID"
        ver: ">Final.Document ID"
        parameters: "=Final.Document Parameters"
        chain.height: 3
        chain.document_ref: "=Last"

        author(Last.Catalyst ID)
    }

    After_Final --|> Last : Invalidly chains to
    style After_Final fill:#100,stroke:#f00,stroke-width:4px
