additional_fields = {
  ? "ref" => ref_type,
  ? "ref_hash" => ref_hash_type,
  ? "template" => ref_type,
  ? "reply" => ref_type,
  ? "section" => text,
  ? "collabs" => [+any],
  ? "brand_id" => ref_type,
  ? "campaign_id" => ref_type,
  ? "election_id" => ref_type,
  ? "category_id" => ref_type,
}

ref_type = UUID / [UUID, UUID] ; UUIDs v7
ref_hash_type = [ref_type, hash-bytes]

UUID = #6.37(bytes)

;# include hash
