; A Choice Selection (clear/unencrypted).
;
; This can be a positive or negative integer, and is
; constrained by the parameters of the contest.


; Universal Unencrypted Set of Choices
clear-choices = ( +clear-choice )

; Universal Unencrypted Choice
clear-choice = uint
