; Proof that values in a column have a required arrangement.
; This is similar to the `row-proof` but for all values in a
; single column.
; It is an array that matches the length of `choices`.
; If it is a different length, then it is invalid.
;
; Currently there are no `column-proof` defined, this value is
; a placeholder for documentation purposes only.
;
; It is NOT to be implemented.
; `column-proof` should be assumed to be missing until such time
; as a concrete `column-proof` is defined.
;
; Similar to `row-proof` there can be multiple column-proofs defined which prove
; certain characteristics of the encrypted column values.
; They are identified by the unsigned integer starting the proof.


; Universal Encrypted Column Proof (Placeholder)
column-proof = [ uint, [ +undefined ] ]
