VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/cddl:v3.2.27 AS cddl-ci

check-cddl:
    FROM cddl-ci+cddl-base

    WORKDIR /cddl

    COPY ./additional_meta.cddl ./hash.cddl ./signed_doc_meta.cddl .

    RUN cddlc -2 hash.cddl
    # RUN cddlc -2 additional_meta.cddl
    # RUN cddlc -2 signed_doc_meta.cddl
