; All encoders/decoders of this specification must follow deterministic cbor encoding rules
; https://datatracker.ietf.org/doc/html/draft-ietf-cbor-cde-06

hash-bytes = (
  #6.32781(bytes) / ; Blake3 hash
  #6.32782(bytes) / ; Blake2b hash
  #6.32783(bytes) ; Blake2s hash
)
