; The reason a document was rejected at this checkpoint.


; The reason a document was rejected at this checkpoint.
rejection-reason = (
    "already-voted" /  ; Used to indicate a voter already voted in another system (ie, Jormungandr)
    "obsolete-vote"    ; Used to indicate a vote that was cast was replaced with a newer vote.
)
