; section_ref


; Reference to a section in a referenced document.
section_ref = json_pointer

; RFC6901 Standard JSON Pointer
; See: https://datatracker.ietf.org/doc/html/rfc6901
json_pointer = text
