VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/cddl:vfeat/python-install-for-base AS cddl-ci

check-cddl:
    FROM cddl-ci+cddl-base

    WORKDIR /cddl

    COPY ./block.cddl ./hash.cddl .

    RUN cddlc -2 hash.cddl
    RUN cddlc -2 block.cddl
