VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/cddl:v3.2.26 AS cddl-ci

check-cddl:
    FROM cddl-ci+cddl-base

    WORKDIR /cddl

    COPY ./block.cddl ./genesis_to_prev_hash.cddl ./hash.cddl .

    RUN cddlc -2 hash.cddl
    RUN cddlc -2 block.cddl
    RUN cddlc -2 genesis_to_prev_hash.cddl
