; All encoders/decoders of this specification must follow deterministic cbor encoding rules
; https://datatracker.ietf.org/doc/html/draft-ietf-cbor-cde-06

genesis-to-prev-hash = [
    chain-id: UUID, ; UUID v7
    timestamp: #6.1(uint .ge 1722470400), ; Epoch-based date/time
    ledger-type: UUID, ; UUID v4
    purpose-id: UUID, ; UUID v7
    validator,
]

UUID = #6.37(bytes) ; UUID type

validator = (kid / [2* kid])
kid = hash-bytes ; hash of the x509/c509 certificate

;# include hash
