; Version 4 UUID
; See: https://www.rfc-editor.org/rfc/rfc9562.html#name-uuid-version-4
;      https://github.com/lucas-clemente/cbor-specs/blob/master/uuid.md


; UUIDv4
uuid_v4 = #6.37(bytes .size 16)
