VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/cddl:feat/cddl AS cddl-ci

check-cddl:
    FROM cddl-ci+cddl-base

    WORKDIR /cddl

    COPY ./docs/src/architecture/08_concepts/catalyst_voting/cddl/gen_vote_tx.cddl .
    COPY ./docs/src/architecture/08_concepts/catalyst_voting/cddl/vote_tx_v2.cddl .

    RUN --no-cache cddlc -2tcddl vote_tx_v2.cddl