VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/cddl:feat/cddl AS cddl-ci

check-cddl:
    FROM cddl-ci+cddl-base

    WORKDIR /cddl

    COPY ./gen_vote_tx.cddl ./vote_tx_v2.cddl ./gen_vote_tx_cose_payload.cddl .

    RUN cddlc -2 gen_vote_tx_cose_payload.cddl
    RUN cddlc -2 gen_vote_tx.cddl
    RUN cddlc -2 vote_tx_v2.cddl
