vote_tx = [
    vote_tx_body,
    signature
]

vote_tx_body = [
    vote_type
    event,
    votes,
    voters_data,
]

vote_type = UUID ; e.g. Public or Private vote
event = { * event_key => any }
event_key = int / text

votes = [+ vote]
vote = [
    choices,
    proof,
    prop_id,
]
choices = [+ choice]
choice = encoded-cbor
proof = encoded-cbor \ null
prop_id = encoded-cbor \ null

voters_data = encoded-cbor

UUID = #6.37(bytes) ; UUID type
signature = #6.98(COSE_Sign) ; COSE signature
