vote-tx-v2 = gen-vote-tx

choice =  #6.24(bstr(choice-data))
proof = #6.24(bstr(proof-data))
prop-id = #6.24(bstr(proposal))

choice-data = public-choice / private-choice

public-choice = uint
private-choice = ciphertext

ciphertext = [group-element, group-element]
group-element = bytes .size 32

proposal = UUID

proof-data = zk-proof

zk-proof = [[+ (announcement, ciphertext, r-response)], scalar]

announcement = (group-element, group-element, group-element)
ciphertext = (group-element, group-element)
r-response = (scalar, scalar, scalar)

scalar = bytes .size 32
group-element = bytes .size 32

;# include gen_vote_tx

