vote-tx-v2<voter-data-t> = gen-vote-tx<choice-data, proof-data, proposal, voter-data-t>

choice-data = encrypted-choice
encrypted-choice = bytes .size 64
proposal = UUID
proof-data = bytes .size (288..) ; 288 is a lower bound which guarantees that proof is not empty 

;# include gen_vote_tx
