block = [
    block_header,
    block_data: metadata,
    validator_signature:metadata,
]

block_header = [
    chain_id: ULID,
    height: int,
    timestamp: #6.1(uint .ge 1722470400), ; Epoch-based date/time
    prev_block_id: hash_bytes, ; hash of the previous block
    ledger_type: UUID,
    purpose_id: ULID / UUID,
    validator: validator,
    metadata: metadata,
]

ULID = #6.32780(bytes) ; ULID type
UUID = #6.37(bytes) ; UUID type

BLAKE_3 = #6.32781(bytes) ; Blake3 hash
BLAKE_2B = #6.32782(bytes) ; Blake2b hash
BLAKE_2S = #6.32783(bytes) ; Blake2s hash

hash_bytes = BLAKE_2B / BLAKE_3 / BLAKE_2S

kid = hash_bytes ; hash of the x509/c509 certificate

validator = (kid / [2* kid])

metadata = [ *any ]

validator_signature = (bytes / [2* bytes])
