VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.1.21 AS rust-ci

# builder : Set up our target toolchains, and copy our files.
builder:
    DO rust-ci+SETUP

    COPY Cargo.toml clippy.toml deny.toml rustfmt.toml .
    COPY --dir .cargo .config c509-certificate cardano-chain-follower cbork hermes-ipfs  .

# check : Run basic check.
check:
    FROM +builder

    DO rust-ci+EXECUTE --cmd="/scripts/std_checks.py"

# build : Build crates.
build:
    FROM +builder

    DO rust-ci+EXECUTE \
        --cmd="/scripts/std_build.py" \
        --args1="--libs=c509-certificate" \
        --args2="--libs=cardano-chain-follower" \
        --args3="--libs=cbork" \
        --args4="--libs=hermes-ipfs" \
        --docs="true"
