VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.2.25 AS rust-ci

COPY_SRC:
    FUNCTION

    COPY --keep-ts --dir \
        Cargo.toml clippy.toml deny.toml rustfmt.toml \
        .cargo .config \
        c509-certificate \
        cardano-blockchain-types \
        cardano-chain-follower \
        catalyst-voting vote-tx-v1 vote-tx-v2 \
        cbork cbork-abnf-parser cbork-cddl-parser \
        hermes-ipfs \
        signed_doc \
        rbac-registration \
        immutable-ledger .

# builder : Set up our target toolchains, and copy our files.
builder:
    DO rust-ci+SETUP
    RUN --no-cache

# sync-cfg: Synchronize local config with CI version.
# Must be run by the developer manually.
sync-cfg:
    FROM +builder
    DO rust-ci+SYNC_STD_CFG

builder-src:
    FROM +builder

    # Don't build the src in the home directory itself, because it contains stuff.
    WORKDIR $HOME/build
    RUN rm -rf *

    # Cached copy of the source we build.
    DO +COPY_SRC

    # Generate Checksums of the source
    DO rust-ci+FINGERPRINT_SRC
    SAVE ARTIFACT ../src_fingerprint.txt

# check : Run basic check.
check:
    FROM +builder-src

    DO rust-ci+EXECUTE --cmd="/scripts/std_checks.py"

# build : Build crates.
build:
    FROM +builder-src

    DO rust-ci+EXECUTE \
        --cmd="/scripts/std_build.py" \
        --args1="--libs=c509-certificate --libs=cardano-blockchain-types --libs=cardano-chain-follower --libs=hermes-ipfs" \
        --args2="--libs=cbork-cddl-parser --libs=cbork-abnf-parser" \
        --args3="--libs=catalyst-voting --libs=vote-tx-v1 --libs=vote-tx-v2" \
        --args4="--bins=cbork/cbork --libs=rbac-registration --libs=signed_doc" \
        --args5="--cov_report=$HOME/build/coverage-report.info" \
        --output="release/[^\./]+" \
        --junit="cat-libs.junit-report.xml" \
        --coverage="cat-libs.coverage.info" \
        --docs="true"

    SAVE ARTIFACT target/$TARGETARCH/doc doc
    SAVE ARTIFACT target/release/cbork cbork

# build-src-check: Check for any caching issues with the source we are building against.
check-builder-src-cache:
    FROM +builder

    # Don't build the src in the home directory itself, because it contains stuff.
    WORKDIR $HOME/build
    RUN rm -rf *

    COPY +builder-src/src_fingerprint.txt ..

    RUN --no-cache echo "Cache Disabled"

    # Uncached copy of the source we build.
    DO +COPY_SRC

    # Generate Checksums of the source
    DO rust-ci+FINGERPRINT_SRC --FINGERPRINT=src_fingerprint_uncached.txt

    RUN diff ../src_fingerprint.txt ../src_fingerprint_uncached.txt \
        || (echo "ERROR: Source fingerprints do not match. Caching Error Detected!!" && exit 1) \
        && echo "Source fingerprints match. Caching OK."


# local-ci-run: This step simulates the full CI run for local purposes only.
local-ci-run:
    BUILD +check
    BUILD +build