# use with https://github.com/casey/just
#
# Hermes developer convenience functions

# cspell: words prereqs, commitlog, rustls, nocapture

default:
    @just --list --unsorted

# Show the dependency tree and all enabled feature flags of every crate.
cargo-tree:
    cargo tree -e features,normal,build -f "{p}[{f}]" --workspace --frozen

# Synchronize STD Configs with the CI Version in use.
sync-cfg:
    earthly +sync-cfg

# Check Dependency licenses and CVE's
license-check:
    cargo deny check --exclude-dev

# Format the rust code
code-format:
    cargo +nightly fmtfix
    cargo +nightly fmtchk

# Lint the rust code
code-lint:
    cargo lintfix -r
    cargo lint -r

# Pre Push Checks
pre-push: sync-cfg code-format code-lint license-check
    # Make sure we can actually build inside Earthly which needs to happen in CI.
    earthly +check
    earthly +build

# Run long running developer test for mithril downloading.
run-mithril-download-example-preprod: code-format code-lint
    cargo build -r --package cardano-chain-follower --example follow_chains --features mimalloc
    RUST_LOG="error,follow_chains=debug,cardano_chain_follower=debug,mithril-client=debug" \
    ./target/release/examples/follow_chains --preprod

run-mithril-download-example-preprod-high-dl-bandwidth: code-format code-lint
    cargo build -r --package cardano-chain-follower --example follow_chains --features mimalloc
    RUST_LOG="error,follow_chains=debug,cardano_chain_follower=debug,mithril-client=debug" \
    ./target/release/examples/follow_chains --preprod --mithril-sync-workers 64 --mithril-sync-chunk-size 16 --mithril-sync-queue-ahead=6

run-mithril-download-example-preprod-conservative-dl-bandwidth: code-format code-lint
    cargo build -r --package cardano-chain-follower --example follow_chains --features mimalloc
    RUST_LOG="error,follow_chains=debug,cardano_chain_follower=debug,mithril-client=debug" \
    ./target/release/examples/follow_chains --preprod --mithril-sync-workers 8 --mithril-sync-chunk-size 1 --mithril-sync-queue-ahead=2

run-mithril-download-example-preview: code-format code-lint
    cargo build -r --package cardano-chain-follower --example follow_chains --features mimalloc
    RUST_LOG="error,follow_chains=debug,cardano_chain_follower=debug,mithril-client=debug" \
    ./target/release/examples/follow_chains --preview

# Run long running developer test for mithril downloading.
run-mithril-download-example-mainnet: code-format code-lint
    cargo build -r --package cardano-chain-follower --example follow_chains --features mimalloc
    RUST_LOG="error,follow_chains=debug,cardano_chain_follower=debug,mithril-client=debug" \
    ./target/release/examples/follow_chains --mainnet

# Run long running developer test for mithril downloading.
debug-heap-mithril-download-example: code-format code-lint
    cargo build --package cardano-chain-follower --example follow_chains
    RUST_LOG="error,follow_chains=debug,cardano_chain_follower=debug,mithril-client=debug" \
    heaptrack ./target/debug/examples/follow_chains --preprod
