# use with https://github.com/casey/just
#
# Hermes developer convenience functions

# cspell: words prereqs, commitlog, rustls, nocapture

default:
    @just --list --unsorted

# Show the dependency tree and all enabled feature flags of every crate.
cargo-tree:
    cargo tree -e features,normal,build -f "{p}[{f}]" --workspace --frozen

# Check Dependency licenses and CVE's
license-check:
    cargo deny check --exclude-dev

# Format the rust code
code-format:
    cargo +nightly fmtfix
    cargo +nightly fmtchk

# Lint the rust code
code-lint:
    cargo lintfix
    cargo lint

# Pre Push Checks
pre-push: code-format code-lint license-check
