# use with https://github.com/casey/just
#
# Hermes developer convenience functions

# cspell: words prereqs, commitlog, rustls, nocapture

default:
    @just --list --unsorted

# Show the dependency tree and all enabled feature flags of every crate.
cargo-tree:
    cargo tree -e features,normal,build -f "{p}[{f}]" --workspace --frozen

# Check Dependency licenses and CVE's
license-check:
    cargo deny check --exclude-dev

# Format the rust code
code-format:
    cargo +nightly fmtfix
    cargo +nightly fmtchk

# Lint the rust code
code-lint:
    cargo lintfix
    cargo lint

# Pre Push Checks
pre-push: code-format code-lint license-check

# Run a get block example for preprod with a specific slot number.
run-get-block-example: code-format
    cargo build -r --package cardano-chain-follower --example follow_chains --features mimalloc
    RUST_LOG="error,follow_chains=debug,cardano_chain_follower=debug,mithril-client=debug" \
    ./target/release/examples/follow_chains get-block preprod 68521586