[package]
name = "hermes-ipfs"
edition.workspace = true
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0.71"
derive_more = {version = "1.0.0", features = ["from","into","display"] }
libipld = "0.16.0"
rust-ipfs = "0.11.21"
tokio = "1.36.0"

[dev-dependencies]
# Dependencies used by examples
clap = { version = "4.5.3", features = ["derive"] }
dirs = "5.0.1"
lipsum = "0.9.1"
rand = "0.8.5"
rustyline-async = "0.4.2"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
