[project]
name = "diagnose-errors"
version = "0.1.0"
description = "CLI tool for diagnosing errors from a transaction error report"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "rich>=14.1.0",
    "rich-argparse>=1.7.1",
]
