VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/python:v3.6.10 AS python-ci

IMPORT ../docs AS docs

# builder - debian plus cue binary
builder:
    FROM python-ci+python-base

    # Eval V3 currently broken with our specifications.
    ENV CUE_EXPERIMENT=evalv3=0

# Copy all the source we need to build the docs
src:
    FROM +builder

    WORKDIR /src
    COPY . .

    SAVE ARTIFACT signed_doc.json

GEN_JSON:
    FUNCTION
    ARG output=../signed_doc.json
    RUN cd definitions; \
        cue vet -Evc -s ./signed_docs/docs:signed_docs && \
        cue export -f -s ./signed_docs/docs:signed_docs --out json | jq -S > $output


# Regenerate the json spec file.
regenerate-json:
    FROM +src

    # Make sure keys are sorted so its both reproducible, AND diffs easily.
    DO +GEN_JSON

    SAVE ARTIFACT --keep-ts signed_doc.json

# Regenerate the full signed document specification json file.
regenerate:
    FROM +src

    COPY +regenerate-json/signed_doc.json .

    RUN cd generators; \
        uv run docs -g -o "../../gen" ../signed_doc.json 

    SAVE ARTIFACT --keep-ts signed_doc.json
    SAVE ARTIFACT --keep-ts ../gen gen

regenerate-local-json:
    FROM +regenerate-json

    SAVE ARTIFACT signed_doc.json AS LOCAL signed_doc.json


regenerate-local:
    FROM +regenerate

    SAVE ARTIFACT ../gen AS LOCAL temp_gen
    SAVE ARTIFACT signed_doc.json AS LOCAL signed_doc.json

# Check that the generated signed docs data matches the src.
# Check the the generated signed docs documentation matches the generated signed docs data
check:
    FROM +src
    RUN cue fmt --check --diff -s --files ./definitions

    # Make sure we can regenerate the same signed doc json
    COPY +regenerate/signed_doc.json signed_doc_regenerated.json
    RUN diff -u signed_doc_regenerated.json signed_doc.json

    # RUN cd definitions; \
    #    cue vet ./cddl 

    # This does not work anymore.  Looks like a bug in the validator.
    # so regenerate and compare the output.
    #RUN cd definitions; \
    #    cue vet ./signed_docs/docs:signed_docs  ../signed_doc.json
    DO +GEN_JSON --output=../signed_doc.check.json
    RUN diff signed_doc.json signed_doc.check.json

    # Get the current docs
    COPY --keep-ts docs+generated-pages/signed_doc /docs

    # Check our validation code actually works properly
    RUN cd generators; \
        uv run docs -o "../../docs" ../signed_doc.json 
