VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/python:v3.4.4 AS python-ci

IMPORT ../docs AS docs

# cspell: words cuelang

# Get cue binary
cue-bin:
    FROM cuelang/cue:0.13.1
    SAVE ARTIFACT /usr/bin/cue


# builder - debian plus cue binary
builder:
    FROM debian:stable-20250203-slim
    COPY +cue-bin/cue /usr/bin/cue

# Copy all the source we need to build the docs
src:
    FROM +builder

    WORKDIR /src
    COPY . .
    ENV CUE_EXPERIMENT="embed"

    SAVE ARTIFACT signed_doc.json

# Check that the generated signed docs data matches the src.
check:
    FROM +src
    RUN cue fmt --check -s --files ./definitions
    RUN cd definitions; CUE_EXPERIMENT=evalv3=0 cue vet ./signed_docs/docs:signed_docs  ../signed_doc.json

# Check the the generated signed docs documentation matches the generated signed docs data
check-docs-generation:
    FROM python-ci+python-base
    COPY ./generators generators
    COPY +src/signed_doc.json .
    COPY --dir docs+generated-signed-docs-pages/signed_doc signed_doc
     # Check our validation code actually works properly
    RUN cd generators; \
        uv run validator ../signed_doc.json
    RUN cd generators; \
        uv run docs -o "../signed_doc" ../signed_doc.json 


#  Regenerate - using the builder
regenerate:
    FROM +src

    RUN cue export -f -s ./signed_docs/docs:signed_docs --out json --outfile signed_doc.json
    SAVE ARTIFACT --keep-ts signed_doc.json AS LOCAL .