# use with https://github.com/casey/just
#
# Developer convenience functions

# required to get cuelang to enable file embedding
export  CUE_EXPERIMENT := "embed"
default:
    @just --list --unsorted

# Fiz (where possible) and format cue files
format:
    cue fix ./signed_docs/docs:signed_docs
    cue fmt --files .

# Check the signed document cue files are valid.
check: format
    cue vet ./signed_docs/docs:signed_docs -c

# Fix and Check Markdown files
regenerate: check
    # Make sure keys are sorted so its both reproducible, AND diffs easily.
    cue export -f -s ./signed_docs/docs:signed_docs --out json | jq -S > signed_doc.json
    cd utility; ./gen_doc_pages.py

# Validate the generated signed_docs.json is correct against the cue schema.
validate:
    cue vet ./signed_docs/docs:signed_docs  signed_doc.json

# Pre Push Checks - intended to be run by a git pre-push hook.
pre-push: regenerate validate
    