VERSION 0.8

IMPORT ../../rust AS rust-workspace

# TODO: This needs reworking, because we no longer have mithril snapshots inside CI.

#local-build:
#    FROM rust-workspace+builder

#    WORKDIR crates/cardano-chain-follower/testbed
#    RUN cargo build -p overhead_benchmark --release

#    SAVE ARTIFACT target/release/overhead_benchmark overhead_benchmark

#local-run-preprod:
#    ARG --required BENCH_NAME

#    FROM +local-build

    #COPY --dir mithril-snapshot-ci+package-preprod-snapshot/snapshot/immutable mithril_snapshot 
    #COPY +build/overhead_benchmark overhead_benchmark_bin
    #RUN ./overhead_benchmark_bin --bench-name $BENCH_NAME --mithril-snapshot-path ./mithril_snapshot

#local-save-preprod-snapshot:
    #FROM mithril-snapshot-ci+package-preprod-snapshot
    #SAVE ARTIFACT immutable AS LOCAL local_preprod_mithril_snapshot 
