VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/python:v3.6.11 AS python-ci

builder:
    FROM python-ci+python-base

    COPY --keep-ts --dir \
        pyproject.toml uv.lock README.md \
        src \
        rust-ffi \
        tests \
        .

build:
    FROM +builder

    RUN uv run maturin develop
    RUN uv run pytest
