VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/python:v3.6.11 AS python-ci
IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.6.11 AS rust-ci

builder:
    DO rust-ci+SETUP
    DO python-ci+INSTALL

    COPY --keep-ts --dir \
        pyproject.toml uv.lock README.md \
        src \
        rust-ffi \
        tests \
        .

build:
    FROM +builder

    RUN uv run maturin develop
    RUN uv run pytest
