VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/docs:v3.6.13 AS docs-ci

IMPORT .. AS repo

# Copy all the source we need to build the docs
src:
    # Common src setup
    DO docs-ci+SRC

    # Now copy into that any artifacts we pull from the builds.
    COPY --dir repo+repo-docs/repo /docs/includes

# Save a copy of the generated doc pages, so they can be validated.
# These need to be in-sync with the signed docs specification data.
generated-pages:
    FROM +src

    SAVE ARTIFACT src/architecture/08_concepts/signed_doc signed_doc


# Build the docs here.
docs:
    FROM +src

    DO docs-ci+BUILD

# local : Create a local image of the document.
local:
    DO docs-ci+PACKAGE

    # Copy the static pages into the container
    COPY +docs/ /usr/share/nginx/html

    # This is a local only image, we do not publish it.
    SAVE IMAGE catalyst-libs-docs:latest
