VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/docs:v3.3.0 AS docs-ci


IMPORT .. AS repo
IMPORT ../specs AS specs

# Copy all the source we need to build the docs
src:
    # Common src setup
    DO docs-ci+SRC

    # Now copy into that any artifacts we pull from the builds.
    COPY --dir repo+repo-docs/repo /docs/includes

    # Copy our generated Signed Document Specification data.
    COPY specs+src/signed_doc.json /docs/includes


# Build the docs here.
docs:
    FROM +src

    DO docs-ci+BUILD

# local : Create a local image of the document.
local:
    DO docs-ci+PACKAGE

    # Copy the static pages into the container
    COPY +docs/ /usr/share/nginx/html

    # This is a local only image, we do not publish it.
    SAVE IMAGE catalyst-libs-docs:latest
