vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 4
    pad: 100
    center: true
  }
}

"Brand Parameters": {
  shape: sql_table
  "content type": application/json
    "type [0]": ebcabeeb-5bc5-4f95-91e8-cab8ca724172


}



"Campaign Parameters": {
  shape: sql_table
  "content type": application/json
    "type [0]": 5ef32d5d-f240-462c-a7a4-ba4af221fa23


}



"Category Parameters": {
  shape: sql_table
  "content type": application/json
    "type [0]": 818938c3-3139-4daa-afe6-974c78488e95


}



"Comment Action Document": {
  shape: sql_table
  "content type": application/json
    "type [0]": 5e60e623-ad02-4a1b-a1ac-406db978ee48
  "type [1]": b679ded3-0e7c-41ba-89f8-da62a17898ea
  "type [2]": a5d232b8-5e03-4117-9afd-be32b878fcdd


}



"Election Parameters": {
  shape: sql_table
  "content type": application/json
    "type [0]": 788ff4c6-d65a-451f-bb33-575fe056b411


}



"Proposal": {
  shape: sql_table
  "content type": application/json
    "type [0]": 7808d2ba-d511-40af-84e8-c0d1625fdfdc

    "category_id": Category Parameters
  "template": Proposal Template

}

"Proposal"."category_id"->"Category Parameters": Optional { style: { stroke: orange } }
"Proposal"."template"->"Proposal Template"


"Proposal Comment": {
  shape: sql_table
  "content type": application/json
    "type [0]": b679ded3-0e7c-41ba-89f8-da62a17898ea
  "type [1]": 7808d2ba-d511-40af-84e8-c0d1625fdfdc

    "category_id": Category Parameters
  "ref": Proposal
  "reply": Proposal Comment
  "template": Proposal Comment Template

}

"Proposal Comment"."category_id"->"Category Parameters": Optional { style: { stroke: orange } }
"Proposal Comment"."ref"->"Proposal"
"Proposal Comment"."reply"->"Proposal Comment": Optional { style: { stroke: orange } }
"Proposal Comment"."template"->"Proposal Comment Template"


"Proposal Comment Meta Template": {
  shape: sql_table
  "content type": application/schema+json
    "type [0]": 0ce8ab38-9258-4fbc-a62e-7faa6e58318f
  "type [1]": 0ce8ab38-9258-4fbc-a62e-7faa6e58318f
  "type [2]": b679ded3-0e7c-41ba-89f8-da62a17898ea
  "type [3]": 7808d2ba-d511-40af-84e8-c0d1625fdfdc

    "category_id": Category Parameters

}

"Proposal Comment Meta Template"."category_id"->"Category Parameters": Optional { style: { stroke: orange } }


"Proposal Comment Template": {
  shape: sql_table
  "content type": application/schema+json
    "type [0]": 0ce8ab38-9258-4fbc-a62e-7faa6e58318f
  "type [1]": b679ded3-0e7c-41ba-89f8-da62a17898ea
  "type [2]": 7808d2ba-d511-40af-84e8-c0d1625fdfdc

    "category_id": Category Parameters
  "template": Proposal Comment Meta Template

}

"Proposal Comment Template"."category_id"->"Category Parameters": Optional { style: { stroke: orange } }
"Proposal Comment Template"."template"->"Proposal Comment Meta Template": Optional { style: { stroke: orange } }


"Proposal Meta Template": {
  shape: sql_table
  "content type": application/schema+json
    "type [0]": 0ce8ab38-9258-4fbc-a62e-7faa6e58318f
  "type [1]": 0ce8ab38-9258-4fbc-a62e-7faa6e58318f
  "type [2]": 7808d2ba-d511-40af-84e8-c0d1625fdfdc

    "category_id": Category Parameters

}

"Proposal Meta Template"."category_id"->"Category Parameters": Optional { style: { stroke: orange } }


"Proposal Moderation Action": {
  shape: sql_table
  "content type": application/json
    "type [0]": 5e60e623-ad02-4a1b-a1ac-406db978ee48
  "type [1]": 7808d2ba-d511-40af-84e8-c0d1625fdfdc
  "type [2]": a5d232b8-5e03-4117-9afd-be32b878fcdd


}



"Proposal Submission Action": {
  shape: sql_table
  "content type": application/json
    "type [0]": 5e60e623-ad02-4a1b-a1ac-406db978ee48
  "type [1]": 7808d2ba-d511-40af-84e8-c0d1625fdfdc
  "type [2]": 78927329-cfd9-4ea1-9c71-0e019b126a65

    "category_id": Category Parameters
  "ref": Proposal

}

"Proposal Submission Action"."category_id"->"Category Parameters"
"Proposal Submission Action"."ref"->"Proposal"


"Proposal Template": {
  shape: sql_table
  "content type": application/schema+json
    "type [0]": 0ce8ab38-9258-4fbc-a62e-7faa6e58318f
  "type [1]": 7808d2ba-d511-40af-84e8-c0d1625fdfdc

    "category_id": Category Parameters
  "template": Proposal Meta Template

}

"Proposal Template"."category_id"->"Category Parameters": Optional { style: { stroke: orange } }
"Proposal Template"."template"->"Proposal Meta Template": Optional { style: { stroke: orange } }
